<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="BOOK-NV4SIBD4NN" failures="2" tests="2" name="Default test(failed)(failed)(failed)(failed)" time="0.105" errors="0" timestamp="17 Jan 2024 03:07:36 GMT">
  <testcase classname="com.testng.test.HowToRunOnlyFailedTest" name="getRun1" time="0.084">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at com.testng.test.HowToRunOnlyFailedTest.getRun1(HowToRunOnlyFailedTest.java:11)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- getRun1 -->
  <testcase classname="com.testng.test.HowToRunOnlyFailedTest" name="getRun2" time="0.001">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at com.testng.test.HowToRunOnlyFailedTest.getRun2(HowToRunOnlyFailedTest.java:16)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- getRun2 -->
  <testcase classname="com.testng.test.HowToRunOnlyFailedTest" name="getRun5" time="0.0">
    <ignored/>
  </testcase> <!-- getRun5 -->
  <testcase classname="com.testng.test.HowToRunOnlyFailedTest" name="getRun3" time="0.0">
    <ignored/>
  </testcase> <!-- getRun3 -->
  <testcase classname="com.testng.test.HowToRunOnlyFailedTest" name="getRun4" time="0.0">
    <ignored/>
  </testcase> <!-- getRun4 -->
</testsuite> <!-- Default test(failed)(failed)(failed)(failed) -->
